<?php
/**
 * Clean-Gab Framework
 * config.php
 * Date: 	2011-01-27
 * Author: 	Leopoldo Barreiro
 */
// Constants

define ("CLEANGAB_FWK_ROOT", "C:\\Dev\\apps\\apache\\htdocs\\cleangab\\core\\");
define ("CLEANGAB_FWK_MODEL", CLEANGAB_FWK_ROOT . "model" . DIRECTORY_SEPARATOR);
define ("CLEANGAB_FWK_ORM", CLEANGAB_FWK_MODEL . "orm" . DIRECTORY_SEPARATOR);
define ("CLEANGAB_FWK_CONTROL", CLEANGAB_FWK_ROOT . "controller" . DIRECTORY_SEPARATOR);
define ("CLEANGAB_FWK_VIEW", CLEANGAB_FWK_ROOT . "view" . DIRECTORY_SEPARATOR);
define ("CLEANGAB_FWK_SECURITY", CLEANGAB_FWK_ROOT . "security" . DIRECTORY_SEPARATOR);
define ("CLEANGAB_FWK_FORMATTER", CLEANGAB_FWK_VIEW . "formatters" . DIRECTORY_SEPARATOR);

require ("localconfig.php");

define ("CLEANGAB_WELCOME", "welcome.php");
define ("CLEANGAB_404", "404.php");
define ("CLEANGAB_501", "501.php");
define ("CLEANGAB_XHTML_TEMPLATE", "base.xhtml");



// Set the new Paths

ini_set ('include_path', 
			ini_get('include_path') . PATH_SEPARATOR . CLEANGAB_FWK_ROOT . PATH_SEPARATOR . CLEANGAB_FWK_CONTROL . PATH_SEPARATOR . 
			CLEANGAB_FWK_MODEL . PATH_SEPARATOR . CLEANGAB_FWK_VIEW . PATH_SEPARATOR . CLEANGAB_FWK_ORM . PATH_SEPARATOR .  
			CLEANGAB_FWK_SECURITY . PATH_SEPARATOR . CLEANGAB_FWK_FORMATTER . PATH_SEPARATOR . CLEANGAB_FWK_ORM . CLEANGAB_DB_DRIVER . DIRECTORY_SEPARATOR . PATH_SEPARATOR);
?>